kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Streamlit App"
paths = ["/"]

[services.development]
run = "python3 -m streamlit run app.py --server.port 5000 --server.address 0.0.0.0"

[services.production]
run = "python3 -m streamlit run app.py --server.port 5000 --server.address 0.0.0.0"

